title: 'Vega Navascués'
default_lang: en
author:
  name: 'Fernanda Fajardo T, Emilio Calderón, Isabel Osegueda'
  email: veganavascues@gmail.com
taxonomies: [category,tag]
metadata:
  description: 'Sitio de Joyería Vega Navascués'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
